# DLS Phoebus settings

# Autoscale databrowser
org.csstudio.trends.databrowser3/use_auto_scale=true

# Archiver URLs
org.csstudio.trends.databrowser3/urls=pbraw://archappl.pri.diamond.ac.uk/retrieval|Primary Archiver Appliance*pbraw://sbarchappl.pri.diamond.ac.uk/retrieval|Standby Archiver Appliance
org.csstudio.trends.databrowser3/archives=pbraw\://archappl.pri.diamond.ac.uk/retrieval|Primary Archiver Appliance